#!/bin/bash

echo "🐕 TrekSnout Image Setup Helper"
echo "================================"
echo ""
echo "This script will help you add your dog images to the website."
echo ""
echo "You need to add these 3 images to the /public/images/ folder:"
echo ""
echo "1. dog-1.jpg - Dog with GPS tracker lying on grass (GPS tracking section)"
echo "2. dog-2.jpg - Two dogs playing in water (Water adventures section)"  
echo "3. dog-3.jpg - Two focused dogs with Jeep (Adventure ready section)"
echo ""
echo "Current status:"
ls -la public/images/*.jpg 2>/dev/null || echo "No image files found yet"
echo ""
echo "To add your images:"
echo "1. Copy your image files to this project directory"
echo "2. Rename them to dog-1.jpg, dog-2.jpg, dog-3.jpg"
echo "3. Move them to the public/images/ folder"
echo ""
echo "Example commands:"
echo "cp /path/to/your/gps-dog-image.jpg public/images/dog-1.jpg"
echo "cp /path/to/your/water-dogs-image.jpg public/images/dog-2.jpg" 
echo "cp /path/to/your/jeep-dogs-image.jpg public/images/dog-3.jpg"
echo ""
echo "Once added, your website will automatically display them with beautiful animations!"
